#pragma once
#define RAW_DEVICE_AREADY_OPENED 0xFFDD1001
#define RAW_DEVICE_OPEN_FAILED 0xFFDD1002
#define RAW_DEVICE_SETUP 0xFFDD1003
#define RAW_DEVICE_GET_COMM_STATE 0xFFDD1004
#define RAW_DEVICE_SET_COMM_TIMEOUT 0xFFDD1005 
#define RAW_DEVICE_BUILD_COMM_DCB 0xFFDD1006
#define RAW_DEVICE_SET_COMM_STATE 0xFFDD1007
#define RAW_DEVICE_CLEAR_BUFFER 0xFFDD1008
#define RAW_DEVICE_NOT_OPENED 0xFFDD1009
#define RAW_DEVICE_WRITE_TIMEOUT 0xFFDD1010
#define RAW_DEVICE_WRITE_ERROR 0xFFDD1011
#define RAW_DEVICE_READ_TIMEOUT 0xFFDD1012
#define RAW_DEVICE_READ_ERROR 0xFFDD1013
#define RAW_DEVICE_CLEAR_ERROR 0xFFDD1014
#define RAW_DEVICE_INVALID_PARAMETER 0xFFDD1015
class CRawDevice
{
	HANDLE m_hHandle;
	HANDLE m_hWriteHandle;
	HANDLE m_hReadHandle;
	DWORD m_dwTimeout;
	CHAR  m_szDCB[1024];
	CHAR  m_szPortName[1024];
public:
	CRawDevice();
	~CRawDevice();
	BOOL IsOpened() CONST;
	LONG Open(CONST CHAR * port, DWORD timeout,CONST CHAR *DCB_string=NULL);
	VOID Close();
	LONG Send(CONST CHAR *data, LONG len);
	LONG Read(CHAR *data, LONG len);
	LONG Exchange(CONST CHAR *input, LONG input_len, CHAR *output, LONG output_len, DWORD timeout, BOOL reconnectFlag=FALSE);
};